-- ============================================================
-- DDL COMPLETO - Hospital La Bendición
-- Base de datos: PostgreSQL
-- ============================================================

CREATE TABLE "especialidad" (
  "id_especialidad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" varchar(255)
);

CREATE TABLE "medico" (
  "id_medico" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "id_especialidad" int NOT NULL,
  "disponible" boolean NOT NULL DEFAULT true,
  "telefono" varchar(20),
  "email" varchar(100)
);

CREATE TABLE "recepcionista" (
  "id_recepcionista" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(100)
);

CREATE TABLE "seguro_medico" (
  "id_seguro" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_aseguradora" varchar(150) NOT NULL,
  "numero_poliza" varchar(80) NOT NULL,
  "fecha_vencimiento" date
);

CREATE TABLE "paciente" (
  "id_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_identificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "fecha_nacimiento" date NOT NULL,
  "direccion" varchar(255) NOT NULL,
  "telefono" varchar(20) NOT NULL,
  "email" varchar(100),
  "id_seguro" int,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "id_recepcionista" int NOT NULL
);

CREATE TABLE "cita" (
  "id_cita" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" int NOT NULL,
  "id_medico" int NOT NULL,
  "id_recepcionista" int NOT NULL,
  "fecha_cita" date NOT NULL,
  "hora_cita" time NOT NULL,
  "ubicacion" varchar(150),
  "estado" varchar(20) NOT NULL DEFAULT 'PENDIENTE',
  "observaciones" varchar(500),
  "fecha_creacion" timestamp NOT NULL DEFAULT (now()),
  -- Validar que el estado solo tenga valores permitidos
  CONSTRAINT chk_estado_cita CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA'))
);

-- *** TABLA NUEVA: usuarios para autenticación JWT ***
CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,      -- se guarda el hash bcrypt
  "rol" varchar(30) NOT NULL,            -- 'ADMIN', 'RECEPCIONISTA', 'MEDICO'
  "activo" boolean NOT NULL DEFAULT true,
  -- Vínculos opcionales al médico o recepcionista real
  "id_medico" int,
  "id_recepcionista" int,
  CONSTRAINT chk_rol_usuario CHECK (rol IN ('ADMIN','RECEPCIONISTA','MEDICO'))
);

-- ============================================================
-- FOREIGN KEYS
-- ============================================================

ALTER TABLE "medico"
  ADD FOREIGN KEY ("id_especialidad") REFERENCES "especialidad"("id_especialidad")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paciente"
  ADD FOREIGN KEY ("id_seguro") REFERENCES "seguro_medico"("id_seguro")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paciente"
  ADD FOREIGN KEY ("id_recepcionista") REFERENCES "recepcionista"("id_recepcionista")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cita"
  ADD FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cita"
  ADD FOREIGN KEY ("id_medico") REFERENCES "medico"("id_medico")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cita"
  ADD FOREIGN KEY ("id_recepcionista") REFERENCES "recepcionista"("id_recepcionista")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario"
  ADD FOREIGN KEY ("id_medico") REFERENCES "medico"("id_medico")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario"
  ADD FOREIGN KEY ("id_recepcionista") REFERENCES "recepcionista"("id_recepcionista")
  DEFERRABLE INITIALLY IMMEDIATE;

-- ============================================================
-- Mejoran la búsqueda
-- ============================================================

CREATE INDEX idx_paciente_identificacion ON paciente(numero_identificacion);
CREATE INDEX idx_cita_fecha ON cita(fecha_cita);
CREATE INDEX idx_cita_paciente ON cita(id_paciente);
CREATE INDEX idx_cita_medico ON cita(id_medico);
